import { ArrowUpRight } from 'lucide-react'
import PageMeta from '../components/PageMeta'
import Reveal from '../components/Reveal'
import { profile as p } from '../data/portfolio'

const years=(start,end)=>`${new Date(start).getFullYear()} — ${end?new Date(end).getFullYear():'Now'}`
export default function About(){ const groups=Object.groupBy?Object.groupBy(p.skills,s=>s.category):p.skills.reduce((a,s)=>((a[s.category]??=[]).push(s),a),{})
return <><PageMeta title="About" description="Cloud infrastructure, networking, and security operations experience, skills, and approach."/><header className="shell grid gap-10 py-20 sm:py-32 lg:grid-cols-[.65fr_1.35fr]"><div><span className="eyebrow">About / Profile</span><p className="mt-8 font-mono text-sm text-muted">{p.location}<br/>In the field since {p.in_field_since}</p></div><Reveal><h1 className="section-title max-w-4xl">Engineer by trade.<br/><span className="text-accent">Operator by habit.</span></h1><p className="prose-copy mt-10">{p.bio}</p></Reveal></header>
<section className="shell py-10 sm:py-20"><div className="grid gap-10 border-t border-line pt-10 lg:grid-cols-[.4fr_1fr]"><div><span className="eyebrow">Experience log</span><h2 className="mt-4 text-3xl">Where I’ve worked.</h2></div><div>{p.experience.map((item,i)=><Reveal key={item.id} className="grid gap-5 border-b border-line py-8 sm:grid-cols-[140px_1fr]" delay={i*.07}><span className="font-mono text-xs text-muted">{years(item.start_date,item.end_date)}</span><div><h3 className="text-2xl">{item.role}</h3><p className="eyebrow mt-2 !text-accent">{item.company}</p><p className="mt-5 leading-7 text-muted">{item.description}</p></div></Reveal>)}{p.education.map(item=><Reveal key={item.id} className="grid gap-5 border-b border-line py-8 sm:grid-cols-[140px_1fr]"><span className="font-mono text-xs text-muted">{years(item.start_date,item.end_date)}</span><div><h3 className="text-2xl">{item.degree} · {item.field}</h3><p className="eyebrow mt-2 !text-accent">{item.institution}</p></div></Reveal>)}</div></div></section>
<section className="shell py-24"><div className="mb-12"><span className="eyebrow">Technical range</span><h2 className="section-title mt-4">What I work with.</h2></div><div className="grid gap-px border border-line bg-line md:grid-cols-2">{Object.entries(groups).map(([category,skills])=><div key={category} className="bg-paper p-7 sm:p-9"><h3 className="text-2xl">{category}</h3><ul className="mt-7 space-y-2.5">{skills.map(skill=><li key={skill.id} className="border-b border-line/60 pb-2.5 font-mono text-xs text-muted last:border-0 last:pb-0">{skill.name}</li>)}</ul></div>)}</div></section>
<section className="shell py-10 sm:py-20"><div className="grid gap-10 border-t border-line pt-10 lg:grid-cols-[.4fr_1fr]"><div><span className="eyebrow">On the record</span><h2 className="mt-4 text-3xl">Awards &amp; certifications.</h2></div><div>{p.achievements.map((item,i)=><Reveal key={item.id} className="grid gap-5 border-b border-line py-8 sm:grid-cols-[140px_1fr]" delay={i*.07}><span className="font-mono text-xs text-muted">{item.period}</span><div><h3 className="text-2xl">{item.title}</h3><p className="mt-4 leading-7 text-muted">{item.detail}</p>{item.link&&<a href={item.link} data-cursor="proof" className="eyebrow mt-5 inline-flex items-center gap-1 hover:text-accent">Certificate <ArrowUpRight size={13}/></a>}</div></Reveal>)}{p.certifications.map(item=><Reveal key={item.id} className="grid gap-5 border-b border-line py-8 sm:grid-cols-[140px_1fr]"><span className="font-mono text-xs text-muted">{item.year}</span><div><h3 className="text-2xl">{item.name}</h3><p className="eyebrow mt-2 !text-accent">{item.issuer}</p>{item.link&&<a href={item.link} data-cursor="proof" className="eyebrow mt-5 inline-flex items-center gap-1 hover:text-accent">Certificate <ArrowUpRight size={13}/></a>}</div></Reveal>)}</div></div></section></> }
