import { ArrowLeft, ArrowUpRight } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import PageMeta from '../components/PageMeta'
import Reveal from '../components/Reveal'
import { getProjectBySlug } from '../data/portfolio'

export default function ProjectDetail(){ const {slug}=useParams(); const p=getProjectBySlug(slug); if(!p) return <div className="shell py-32"><h1 className="section-title">Project not found.</h1><Link className="button mt-8" to="/projects">Back to projects</Link></div>
return <><PageMeta title={p.title} description={p.short_description}/><header className="shell py-16 sm:py-28"><Link to="/projects" data-cursor="back" className="eyebrow inline-flex items-center gap-2 hover:text-accent"><ArrowLeft size={14}/> All projects</Link><Reveal className="mt-16"><h1 className="display max-w-6xl">{p.title}</h1><div className="mt-10 grid gap-8 border-t border-line pt-8 md:grid-cols-2"><p className="text-xl leading-8 sm:text-2xl">{p.short_description}</p><div className="flex flex-wrap content-start gap-2 md:justify-end">{p.tech_stack.map(t=><span key={t.id||t.name} className="border border-line px-3 py-1.5 font-mono text-[10px] uppercase">{t.name}</span>)}</div></div></Reveal></header>
<div className="border-y border-line bg-ink py-24 text-paper"><div className="shell grid gap-16 md:grid-cols-2"><Reveal><span className="eyebrow !text-paper/50">01 / The problem</span><h2 className="mt-6 text-4xl">What needed to change.</h2><p className="mt-7 text-lg leading-8 text-paper/70">{p.problem}</p></Reveal><Reveal delay={.08}><span className="eyebrow !text-paper/50">02 / The response</span><h2 className="mt-6 text-4xl">A system, not a patch.</h2><p className="mt-7 text-lg leading-8 text-paper/70">{p.solution}</p></Reveal></div></div>
<section className="shell py-24"><div className="grid gap-16 border-y border-line py-16 md:grid-cols-2"><div><span className="eyebrow">Challenges</span><p className="mt-5 text-lg leading-8 text-muted">{p.challenges}</p></div><div><span className="eyebrow">Learnings</span><p className="mt-5 text-lg leading-8 text-muted">{p.learnings}</p></div></div><div className="mt-12 flex flex-wrap gap-3">{p.live_url&&<a className="button" data-cursor="go live" href={p.live_url}>View live <ArrowUpRight size={15}/></a>}{p.github_url&&<a className="button button-ghost" data-cursor="code" href={p.github_url}>Source code <ArrowUpRight size={15}/></a>}</div></section></> }
